---
- hosts: webserver
  become: true
  tasks:
  
  - name: Install epel, JDK & Tomcat 
    yum: name=java-1.8.0-openjdk state=present update_cache=yes
      
  - name: Install EPEL repo.
    yum:
      name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
      state: present

  - name: Install tomcat
    yum: name=tomcat state=present update_cache=yes


  - name: Install tomcat webapps
    yum: name=tomcat-webapps 

  - name: Install tomcat admin-webapps
    yum: 
      name=tomcat-admin-webapps 
      state=present

  - name: Delete tomcat-users.xml
    file:
      path: /etc/tomcat/tomcat-users.xml
      state: absent

  - name: Copy tomcat-users.xml from Ansible Control Machine
    copy:
      src: tomcat-users.xml
      dest: /etc/tomcat/

  - name: Restart tomcat
    service: name=tomcat state=restarted

  - name: Stop IPtables
    service: name=iptables state=stopped

  - name: Copy artidacts from NEXUS
    get_url:
      url: http://18.218.174.206:8081/nexus/service/local/repositories/ansible/content/dev/gol/{{BUILD_ID}}-{{BUILD_TIMESTAMP}}/{{artifact_id}}-{{my_version}}.war
      dest: /usr/share/tomcat/webapps/
      
      
    
